### ISSUE TITLE
In which case(s) does graceful-fs allow errors which this catches?

### ISSUE THREAD

**Issue by adam-lynch** [bevry/safefs#7]

**Comment by balupton** [comment]
Not sure if the docs https://github.com/bevry/safefs#usage existed before, but this covers what is added.

For a bit of background, this module was actually created in the node 0.4 days (when graceful-fs didn't exist), these days we use graceful-fs with the bits of extras that we still keep, as documented in the usage.

**Comment by adam-lynch** [comment]
Thanks!
